# Generated by Django 2.2 on 2020-03-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coronaapi', '0002_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
