# Generated by Django 2.2 on 2020-03-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronaapi', '0003_delete_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Parent id used for cities')),
                ('displayName', models.CharField(blank=True, max_length=250, null=True, verbose_name='Display Name on web')),
                ('totalConfirmed', models.IntegerField(blank=True, max_length=250, null=True, verbose_name='Total confirm cases in country')),
                ('totalDeaths', models.IntegerField(blank=True, max_length=250, null=True, verbose_name='Total death cases in country')),
                ('totalRecovered', models.IntegerField(blank=True, max_length=250, null=True, verbose_name='Total recovered cases in country')),
                ('lastUpdated', models.CharField(blank=True, max_length=250, null=True, verbose_name='Last update date time')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude of country')),
                ('long', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude of country')),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Country name')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Parent id used for cities')),
                ('displayName', models.CharField(blank=True, max_length=250, null=True, verbose_name='Display Name on web')),
                ('totalConfirmed', models.IntegerField(blank=True, max_length=250, null=True, verbose_name='Total confirm cases in country')),
                ('totalDeaths', models.IntegerField(blank=True, max_length=250, null=True, verbose_name='Total death cases in country')),
                ('totalRecovered', models.IntegerField(blank=True, max_length=250, null=True, verbose_name='Total recovered cases in country')),
                ('lastUpdated', models.CharField(blank=True, max_length=250, null=True, verbose_name='Last update date time')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude of country')),
                ('long', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude of country')),
            ],
        ),
    ]
