# Generated by Django 2.2 on 2020-03-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronaapi', '0004_area_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='totalConfirmed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total confirm cases in country'),
        ),
        migrations.AlterField(
            model_name='area',
            name='totalDeaths',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total death cases in country'),
        ),
        migrations.AlterField(
            model_name='area',
            name='totalRecovered',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total recovered cases in country'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='totalConfirmed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total confirm cases in country'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='totalDeaths',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total death cases in country'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='totalRecovered',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total recovered cases in country'),
        ),
    ]
