# Generated by Django 2.2 on 2020-03-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0002_auto_20200311_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='location and region'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Last Name'),
        ),
    ]
