# Generated by Django 2.2 on 2020-03-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0003_auto_20200311_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Email of the user'),
        ),
    ]
