# Generated by Django 2.2 on 2020-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0004_auto_20200311_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='infection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of infection')),
                ('start_hour', models.CharField(blank=True, max_length=100, null=True, verbose_name='Star Hour')),
                ('end_hour', models.CharField(blank=True, max_length=100, null=True, verbose_name='End Hour')),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('place_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place Type')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('type', models.CharField(blank=True, choices=[('Single', 'Single'), ('Route', 'Route')], max_length=100, null=True, verbose_name='Location')),
                ('route_id', models.CharField(blank=True, choices=[('Single POI ', 'Single POI'), ('List of POIs ', 'List of POIs')], max_length=100, null=True, verbose_name='Location')),
            ],
        ),
    ]
