# Generated by Django 2.2 on 2020-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0006_auto_20200311_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='infection',
            name='add_route_point',
            field=models.URLField(default='route.mp', verbose_name='Route point link'),
        ),
        migrations.AddField(
            model_name='infection',
            name='add_single_point',
            field=models.URLField(default='map.mp', verbose_name='Single point link'),
        ),
        migrations.AlterField(
            model_name='infection',
            name='route_id',
            field=models.CharField(blank=True, choices=[('Single POI ', 'Single POI'), ('List of POIs ', 'List of POIs')], max_length=100, null=True, verbose_name='Route ID'),
        ),
    ]
