# Generated by Django 2.2 on 2020-03-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0008_auto_20200312_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infection',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='infection',
            name='type',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Route', 'Route')], max_length=100, null=True, verbose_name='Place Type'),
        ),
    ]
