# Generated by Django 2.2 on 2020-03-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0009_auto_20200312_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of tavel')),
                ('arrival_place', models.CharField(blank=True, max_length=250, null=True, verbose_name='Transport arrival place')),
                ('departure_place', models.CharField(blank=True, max_length=250, null=True, verbose_name='Transport departure place')),
                ('arrival_time', models.CharField(blank=True, max_length=250, null=True, verbose_name='Transport arrival time')),
                ('departure_time', models.CharField(blank=True, max_length=250, null=True, verbose_name='Transport departure time')),
                ('transport_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Bus train flight number')),
                ('transport_mode', models.CharField(blank=True, choices=[('Bus', 'Bus'), ('Train', 'Train'), ('Flight', 'Flight')], max_length=250, null=True, verbose_name='Mode of transport ')),
            ],
        ),
    ]
