# Generated by Django 2.2 on 2020-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0010_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='infection',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Info about coronavirus'),
        ),
    ]
