# Generated by Django 2.2 on 2020-03-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0011_infection_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='arrival_country',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Transport arrival Country'),
        ),
        migrations.AddField(
            model_name='transport',
            name='departure_country',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Transport departure Country'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='arrival_place',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Transport arrival city'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='departure_place',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Transport departure city'),
        ),
    ]
