# Generated by Django 2.2 on 2020-03-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0012_auto_20200317_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Flight company name'),
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
