# Generated by Django 2.2 on 2020-03-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0013_auto_20200319_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='infection',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='infection',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City name or state'),
        ),
    ]
